### PR TITLE
Fix #397: Handle error on load of drive files.

### LINKED ISSUE #397: Wall crashes when drive file is missing.
```
I 2022-12-15T21:30:00.291Z 118211864.0: [slideshow:drive] Received drive init for some client
I 2022-12-15T21:30:00.329Z 118211902.0: [slideshow:google_auth] Access token refreshed.
error: Uncaught Error: Error when getting info about drive file: Not Found
    throw new Error(
          ^
    at driveFilesList (file:///home/walle/wall/releases/videowall-1670923011-1a051f26283ccdce54b396df899641f77473ba96/videowall/chicago-brick/demo_modules/slideshow/load_from_drive_server.ts:47:11)
    at async Object.start (file:///home/walle/wall/releases/videowall-1670923011-1a051f26283ccdce54b396df899641f77473ba96/videowall/chicago-brick/demo_modules/slideshow/load_from_drive_server.ts:82:32)
```

### PR DESCRIPTION
**Pull request by applmak**
- If we are trying to load a folder and drive can't find the folder, we now skip that folder.

### CODE REVIEW

File: demo_modules/slideshow/load_from_drive_server.ts [hunk 1]
```diff
@@ -79,7 +79,15 @@ class DriveItemsDownloader {
...
               }
-              const response = await driveFilesList(client, req);
+              let response: FileList;
+              try {
+                response = await driveFilesList(client, req);
+              } catch (e) {
+                log.error(
+                  `Unable to download files in folder: ${folderId}: ${e.message}`,
+                );
+                break;
```
Comment (g-harel) [inline demo_modules/slideshow/load_from_drive_server.ts:89]: Just to clarify, what happens if no files load, will the screen go blank?

Comment (g-harel) [reply demo_modules/slideshow/load_from_drive_server.ts:89]: Hm ok eventually we should probably make it revert to default or something. Thanks for fixing this!

**Review by g-harel — APPROVED** [review]
